export const ACTION_TYPE = {
  GIT_HUB_SEARCH: 'GIT_HUB_SEARCH',
  BOOKMARK:"BOOKMARK",
};

export const API_ACTION_TYPE = {
  API: 'API',
  API_START: 'API_START',
  API_END: 'API_END',
  ACCESS_DENIED: 'ACCESS_DENIED',
  API_ERROR: 'API_ERROR',
};
